# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Kyusik Jeong
tagline:          'Portfolio'
description:      ''
url:              https://skycircle860.github.io/
baseurl:          /

author:
  name:           ''
  url:            /

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://skycircle860.github.io/
