# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Kyusik Jeong
tagline:          'A Jekyll theme'
description:      '숙련된 개발자를 꿈꾸며...'
url:              https://skycircle860.github.io/
baseurl:          /

author:
  name:           'Mark Otto'
  url:            /

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://skycircle860.github.io/
